services:
  php:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-debug}
    extra_hosts:
      - host.docker.internal:host-gateway
    user: ${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}