name: "Tests"
on: push
env:
  DOCKER_BUILDKIT: 1
jobs:
  build-backend:
    name: "QA Pipeline"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.3' ]
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zip, json
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: PHPUnit
        run: php ./vendor/bin/phpunit

      - name: PHPStan
        run: php ./vendor/bin/phpstan analyse --configuration ./phpstan.dist.neon --no-progress

      - name: PHP-CS-Fixer
        run: PHP_CS_FIXER_IGNORE_ENV=1 php ./vendor/bin/php-cs-fixer fix --config=./.php-cs-fixer.dist.php --allow-risky=yes --dry-run --diff
